backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
i18n:
  structure: multiple_folders
  locales: [en, fr]
  default_locale: fr

collections:
  - name: pages 
    label: Homepage
    folder: public/locales
    extension: json
    i18n: true
    fields: 
      - { label: Share Image, name: meta_image, widget: image }
      - { label: Share Description, name: meta_desc, widget: string, i18n: true }
      - { label: Address, name: address, widget: string, i18n: true }
      - { label: Instagram URL, name: ig_url, widget: string }
      - { label: Reservations Label, name: rsv_label, widget: string, i18n: true }
      - { label: Reservations URL, name: rsv_url, widget: string }